Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [2]:
import numpy as np

List Numpy -> Time Taken

In [3]:
from time import process_time

In [4]:
python_list = [i for i in range(10)]
print(python_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
python_list1 = [i+5 for i in python_list]
print(python_list1)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


Time Taken by a list

In [6]:


list = [i for i in range(1000000)]

start_time = process_time()

list = [i+5 for i in list]

end_time = process_time()

print(end_time - start_time)

0.0625


In [7]:

np_array = np.array([i for i in range(10)])
print(np_array)

np_array +=5

print(np_array)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [8]:


np_array = np.array([i for i in range(1000000)])


start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0


In [9]:
np_array = np.array([1,2,3,4,5,62])

print(np_array)
type(np_array)


[ 1  2  3  4  5 62]


numpy.ndarray

In [10]:
np_array.shape

(6,)

In [11]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [12]:
type(b)

numpy.ndarray

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays
NumPy-তে আমরা অনেক সময় শুরুতেই কিছু খালি/ডিফল্ট value দিয়ে filled array তৈরি করি। এগুলোকে initial placeholders বলে।

In [14]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# array of a particular value
z = np.full((4,5),10)
print(z)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [17]:
# create an identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# create a numpy array with random values
b = np.random.random((4,3))
print(b)



[[0.62702426 0.51847694 0.42793009]
 [0.84781448 0.21062083 0.39830536]
 [0.31708803 0.22277962 0.82457638]
 [0.63260022 0.69629416 0.42778821]]


In [19]:
c = np.random.randint(10,20,(4,3))  #20 exclusive
print(c)

[[14 18 17]
 [19 14 15]
 [14 19 10]
 [15 19 17]]


In [20]:
# array of evenly spaced values --> specifying the number of values required , end value included
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# array of evenly spaced values --> specifying the step , end value exlueded
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [23]:
c = np.random.randint(10,90,(5,5))
print(c)

[[86 21 27 76 28]
 [63 84 59 76 54]
 [12 70 71 89 48]
 [16 87 19 52 89]
 [26 43 16 38 55]]


In [24]:
# array dimension
print(c.shape)

(5, 5)


In [25]:
# number of dimensions
print(c.ndim)

2


In [26]:
# number of elements in an array
print(c.size)

25


In [27]:
# checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array

In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 22 24]
 [16 21 23]
 [25 21 25]]
[[-10 -14 -14]
 [ -4 -15 -15]
 [-13 -11 -11]]
[[ 96  72  95]
 [ 60  54  76]
 [114  80 126]]
[[0.375      0.22222222 0.26315789]
 [0.6        0.16666667 0.21052632]
 [0.31578947 0.3125     0.38888889]]


In [30]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 22 24]
 [16 21 23]
 [25 21 25]]
[[-10 -14 -14]
 [ -4 -15 -15]
 [-13 -11 -11]]
[[ 96  72  95]
 [ 60  54  76]
 [114  80 126]]
[[0.375      0.22222222 0.26315789]
 [0.6        0.16666667 0.21052632]
 [0.31578947 0.3125     0.38888889]]


Array Manipulation

In [31]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 5 1]
 [3 2 5]]
(2, 3)


In [32]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 3]
 [5 2]
 [1 5]]
(3, 2)


In [33]:
#transpose
trans = array.T
print(trans)
print(trans.shape)

[[1 3]
 [5 2]
 [1 5]]
(3, 2)


In [34]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 5 4]
 [7 8 2]]
(2, 3)


In [35]:
c = np.array([1,2,3,4,5,6])
b = c.reshape(3,2)
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


flatten() হলো NumPy array-এর একটি method, যা multi-dimensional array কে 1D array-এ রূপান্তর করে।

In [36]:
a = np.array([
    [1, 2],
    [3, 4]
])

print(a.flatten())

[1 2 3 4]
