In [1]:
import numpy as np

Creating a Matrix using numpy 

In [2]:
mat = np.array([[2,3],[6,7]])
print(mat)

[[2 3]
 [6 7]]


In [4]:
mat.shape

(2, 2)

In [5]:
mat2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(mat2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


Creating Matrices with Random Values

In [ ]:
random_mat = np.random.rand(3,3)
#random_mat = np.random.random((3,3)) # It's do the same work just syntax different
print(random_mat)

[[0.13039441 0.18388698 0.81789444]
 [0.82927232 0.62355122 0.0167116 ]
 [0.60609648 0.62330847 0.82330063]]


In [12]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100 , size=(4,5))
#random_integer_matrix = np.random.randint( 20,100 , size=(4,5)) do same work but integer range 20 to 100
print(random_integer_matrix)

[[ 1  7  7  6 75]
 [24 41 87 26 28]
 [14 11 25 53 99]
 [81 38 87 55 77]]


Matrix with all the values as 1

In [13]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
matrix_3 = np.ones((2,3),dtype =int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null Matrix or Zero Matrix

In [15]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
null_matrix = np.zeros((4,4), dtype = int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity Matrix

In [17]:
identity_matrix = np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
identity_matrix = np.eye(5, dtype = int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Transpose of a Matrix

In [24]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[45 38  7 73  7]
 [ 4 30 94 29 47]
 [87 92 74 39 77]
 [25 20 17 80  8]]


In [ ]:
tranpose = np.transpose(a)
#tranpose = a.T # this is also use for tranpose Matrix
print(tranpose)

[[45  4 87 25]
 [38 30 92 20]
 [ 7 94 74 17]
 [73 29 39 80]
 [ 7 47 77  8]]


Matrix Addition

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

#sum = A + B  # It's do the same work
sum = np.add(A,B)
print(sum)

[[ 8 10]
 [12 14]]


In [29]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

**Matrix Subtraction**

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

#diff = A - B   # It's also do the same work
diff = np.subtract(A,B)

print(diff)

[[-4 -4]
 [-4 -4]]


**Multiplying a matrix by a scalar**

In [32]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[6 0 6 9]
 [6 4 3 7]
 [6 6 4 1]
 [1 9 7 7]]


In [34]:
product = np.multiply(x,y)

print(product)

[[30  0 30 45]
 [30 20 15 35]
 [30 30 20  5]
 [ 5 45 35 35]]


**Multiplying 2 Matrices**

In [42]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))
print(matrix_3)
print(matrix_4)

[[3 1 2]
 [0 3 2]
 [3 3 4]]
[[3 4 1]
 [3 2 4]
 [2 4 0]]


In [43]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[16 22  7]
 [13 14 12]
 [26 34 15]]


Element wise Multiplication

In [45]:
product = np.multiply(matrix_4,matrix_3)
print(product)

[[ 9  4  2]
 [ 0  6  8]
 [ 6 12  0]]
