Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [12]:
import numpy as np

List Numpy -> Time Taken

In [7]:
from time import process_time

In [3]:
python_list = [i for i in range(10)]
print(python_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
python_list1 = [i+5 for i in python_list]
print(python_list1)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


Time Taken by a list

In [10]:


list = [i for i in range(1000000)]

start_time = process_time()

list = [i+5 for i in list]

end_time = process_time()

print(end_time - start_time)

0.0625


In [14]:

np_array = np.array([i for i in range(10)])
print(np_array)

np_array +=5

print(np_array)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:


np_array = np.array([i for i in range(1000000)])


start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0


In [17]:
np_array = np.array([1,2,3,4,5,62])

print(np_array)
type(np_array)


[ 1  2  3  4  5 62]


numpy.ndarray

In [18]:
np_array.shape

(6,)

In [20]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [21]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays
NumPy-তে আমরা অনেক সময় শুরুতেই কিছু খালি/ডিফল্ট value দিয়ে filled array তৈরি করি। এগুলোকে initial placeholders বলে।

In [25]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# array of a particular value
z = np.full((4,5),10)
print(z)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [28]:
# create an identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
# create a numpy array with random values
b = np.random.random((4,3))
print(b)



[[0.55508062 0.93464494 0.06962584]
 [0.36371197 0.55087827 0.23401972]
 [0.87184669 0.24952199 0.93697522]
 [0.52161861 0.10236695 0.78926839]]


In [ ]:
c = np.random.randint(10,20,(4,3))  #20 exclusive
print(c)

[[16 16 14]
 [19 16 11]
 [18 16 14]
 [17 19 19]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required , end value included
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [37]:
# array of evenly spaced values --> specifying the step , end value exlueded
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [38]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [41]:
c = np.random.randint(10,90,(5,5))
print(c)

[[66 19 12 11 75]
 [41 80 23 72 63]
 [89 77 40 63 74]
 [89 29 11 36 52]
 [27 78 16 26 76]]


In [46]:
# array dimension
print(c.shape)

(5, 5)


In [47]:
# number of dimensions
print(c.ndim)

2


In [48]:
# number of elements in an array
print(c.size)

25


In [49]:
# checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array

In [50]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [51]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[23 19 22]
 [17 22 17]
 [13 20 24]]
[[-13  -1  -6]
 [-11  -6 -15]
 [ -9 -16  -6]]
[[ 90  90 112]
 [ 42 112  16]
 [ 22  36 135]]
[[0.27777778 0.9        0.57142857]
 [0.21428571 0.57142857 0.0625    ]
 [0.18181818 0.11111111 0.6       ]]


In [54]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 19 22]
 [17 22 17]
 [13 20 24]]
[[-13  -1  -6]
 [-11  -6 -15]
 [ -9 -16  -6]]
[[ 90  90 112]
 [ 42 112  16]
 [ 22  36 135]]
[[0.27777778 0.9        0.57142857]
 [0.21428571 0.57142857 0.0625    ]
 [0.18181818 0.11111111 0.6       ]]


Array Manipulation

In [55]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 5 7]
 [1 0 6]]
(2, 3)


In [57]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 1]
 [5 0]
 [7 6]]
(3, 2)


In [58]:
#transpose
trans = array.T
print(trans)
print(trans.shape)

[[2 1]
 [5 0]
 [7 6]]
(3, 2)


In [59]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 8 5]
 [8 7 7]]
(2, 3)


In [60]:
c = np.array([1,2,3,4,5,6])
b = c.reshape(3,2)
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
